# Generated by Django 4.2.7 on 2023-11-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_login_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pswrd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
